security:
  basic:
    enabled: false # turn off securing our application endpoints

management:
  security:
    enabled: false # turn off securing the actuator endpoints

greeting:
  displayFortune: false

quoteServiceURL: http://quote-service-dev.cfapps.io/quote
